### ISSUE TITLE
Fix Swift 5.0 warnings

### ISSUE THREAD

**Issue by delbyze** [tristanhimmelman/ObjectMapper#1054] opened 2019-05-16 12:17 UTC
Please, can you fix Swift 5.0 warnings ?

<img width="435" alt="Capture d’écran 2019-05-16 à 14 14 51" src="https://user-images.githubusercontent.com/38207269/57853130-4461ff80-77e5-11e9-8da8-ce5f48950402.png">
<img width="433" alt="Capture d’écran 2019-05-16 à 14 14 40" src="https://user-images.githubusercontent.com/38207269/57853137-47f58680-77e5-11e9-9fda-dfabe1552ea1.png">

**Comment by abdullah-s** [comment] 2019-05-16 21:05
Duplicate of #1043

**Comment by RomanPodymov** [comment] 2019-05-17 16:59
Hello @delbyze 
The issue has been fixed in [this pull request](https://github.com/tristanhimmelman/ObjectMapper/pull/1044). The branch was already merged to master. Just replace `pod 'ObjectMapper'` with `pod 'ObjectMapper', :git => 'https://github.com/tristanhimmelman/ObjectMapper.git', :branch => 'master'` in your Podfile.

**Closed** 2019-05-22 11:27 UTC

**Comment by tbechtum** [comment] 2019-06-12 10:22
Installed today ObjectMapper 3.5.0 and there no more these Xcode 10.2.1 / Swift 5 warnings, thanks.

**Comment by RomanPodymov** [comment] 2019-06-12 10:30
@tbechtum Great, you can close the issue.
